branches:
 only:
  - master
  - /^[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$/
  - arm64_wheel

language: python

matrix:
  include:

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7.4

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.15
        
    - os: linux
      arch: arm64
      dist: bionic
      sudo: required
      env:
        - PYTHON_VERSION=3.7.4

      deploy:
        - provider: releases
        - api_key: 
            secure: 16db94c1564bdc5955e24d57da431815cc720f34
        - file: dist/*.whl
        - edge: true
        - skip_cleanup: true
        - on:
           tags: true

cache:
  directories:
    - $HOME/.pyenv/versions/3.7.4
    - $HOME/.pyenv/versions/2.7.15
    - $HOME/downloads

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir $HOME/bin; ln -s $(which pip2) $HOME/bin/pip; ln -s $(which python2) $HOME/bin/python; fi
  - python scripts/ssl-check.py
  - python -m pip install --disable-pip-version-check --upgrade pip
  - pip install -U scikit-ci scikit-ci-addons 
  - ci_addons --install ../addons

install:
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
       pip install scikit-build;
       python setup.py bdist_wheel;
       ls dist/ ;
    else
       ci install;
    fi

script:
  - if [ "${TRAVIS_CPU_ARCH}" != "arm64" ]; then
       ci test;
    fi

after_success:
  - if [ "${TRAVIS_CPU_ARCH}" != "arm64" ]; then
       ci after_test;
    fi
