branches:
 only:
  - master
  - /^[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$/
  - arm64_wheel

language: python

matrix:
  include:

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7.4

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.15
        
    - os: linux
      arch: arm64
      dist: bionic
      sudo: required
      python: "3.7"
      env:
        - PYTHON_VERSION=3.7.4

      before_deploy:
        - git config --global user.name "odidev"
        - git config --global user.email "odidev@puresoftware.com"
        - git config --global --list
        - export TRAVIS_TAG=aarch64-python-wheels-1.0
        - git tag $TRAVIS_TAG
        - python setup.py bdist_wheel

      deploy:
        provider: releases
        api_key: 
          secure: U2FS/+pvbrtWwSvHpL/fbz48HyexWmV8c1x6YbgFyilElSkHv/OBmD/4p3vOSm4LVREpysOeT45zd+WgoH48COt+TFzOPxYEBGA5SDZtTFP2dResSzvxyxSi983vPIXFPt+o8c5uTjFzXqjmvAs318AqUImzEUK3f2/7XHGckbMdV3OLBz63SYM7A0NnBYefYec3sMD1UAMJte+lGRyQBdYVGViXHDECgOv3L3iNzrw7kAS1IzqgUPaCA898ZSiu+yTsQaX75e8awGrRrZdBEJs1f+j2KvwqIJhbTBwlWxBph6wy/0rWW5zxE4dDu9DT6hcEBc2OPIqDy0Aqss1oWfimnb9cyKnFX31fGVrrty+w+slHhabX5WQu4A0YAvrfD37yXb8Ky9csw3ZI/8o/llxlmuXTqnuGxg4oMxzSqniVvdC63/5SsUTPMg4t/c9uIxgKgO2U3t7YlA3YfdsdRAOMOKhCY82vTPdZOjJXqIIS/9GHio4Q3UgUa5wWlnxiW/l/eyne7cBRHlbCV9OGRFJYxI5nRttM6HcX8EuU3Pqle7P4akD2wSpEumM/wXud/eL5JBdD7gnlHCQ0tjglwUqTPUzkKIwJtF5u1imj7x/x6dqnJGYtIMNDGKDXnKnt9KmYLk2X0NolJk27qp0u9wcTGoHUh4WiHgTBOUTGgGg=
        file_glob: true
        file: ./dist/*.whl
        skip_cleanup: true
        on:
           repo: odidev/cmake-python-distributions

cache:
  directories:
    - $HOME/.pyenv/versions/3.7.4
    - $HOME/.pyenv/versions/2.7.15
    - $HOME/downloads

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir $HOME/bin; ln -s $(which pip2) $HOME/bin/pip; ln -s $(which python2) $HOME/bin/python; fi
  - python scripts/ssl-check.py
  - python -m pip install --disable-pip-version-check --upgrade pip
  - pip install -U scikit-ci scikit-ci-addons 
  - ci_addons --install ../addons

install:
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
       pip install scikit-build;
    else
       ci install;
    fi

script:
  - if [ "${TRAVIS_CPU_ARCH}" != "arm64" ]; then
       ci test;
    fi

after_success:
  - if [ "${TRAVIS_CPU_ARCH}" != "arm64" ]; then
       ci after_test;
    fi
