branches:
 only:
  - master
  - /^[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$/

language: python

matrix:
  include:

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7.4

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.15
        
    - os: linux
      arch: arm64
      env:
        - PYTHON_VERSION=3.7.4

cache:
  directories:
    - $HOME/.pyenv/versions/3.7.4
    - $HOME/.pyenv/versions/2.7.15
    - $HOME/downloads

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir $HOME/bin; ln -s $(which pip2) $HOME/bin/pip; ln -s $(which python2) $HOME/bin/python; fi
  - python scripts/ssl-check.py
  - python -m pip install --disable-pip-version-check --upgrade pip
  - pip install -U scikit-ci scikit-ci-addons
  - ci_addons --install ../addons

install:
  - ci install
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
      python setup.py bdist_wheel;
      ls dist;
    fi

script:
  - ci test

after_success:
  - ci after_test
